In [2]:
import pandas as pd
import numpy as np

In [3]:
import os
print(os.getcwd())

/home/krish/AI-Interview-Intelligence-Platform/notebooks

In [4]:
resume_df = pd.read_csv(
    "../datasets/raw/resumes/Resume.csv"
)

In [5]:
resume_df.head()

,ID,Resume_str,Resume_html,Category
0,16852973,HR ADMINISTRATOR/MARKETING ASSOCIATE\...,"<div class=""fontsize fontface vmargins hmargin...",HR
1,22323967,"HR SPECIALIST, US HR OPERATIONS ...","<div class=""fontsize fontface vmargins hmargin...",HR
2,33176873,HR DIRECTOR Summary Over 2...,"<div class=""fontsize fontface vmargins hmargin...",HR
3,27018550,HR SPECIALIST Summary Dedica...,"<div class=""fontsize fontface vmargins hmargin...",HR
4,17812897,HR MANAGER Skill Highlights ...,"<div class=""fontsize fontface vmargins hmargin...",HR

In [6]:
resume_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2484 entries, 0 to 2483
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ID           2484 non-null   int64
 1   Resume_str   2484 non-null   str
 2   Resume_html  2484 non-null   str
 3   Category     2484 non-null   str
dtypes: int64(1), str(3)
memory usage: 77.8 KB

In [7]:
resume_df["Category"].value_counts()

Category
INFORMATION-TECHNOLOGY    120
BUSINESS-DEVELOPMENT      120
ADVOCATE                  118
CHEF                      118
FINANCE                   118
ENGINEERING               118
ACCOUNTANT                118
FITNESS                   117
AVIATION                  117
SALES                     116
HEALTHCARE                115
CONSULTANT                115
BANKING                   115
CONSTRUCTION              112
PUBLIC-RELATIONS          111
HR                        110
DESIGNER                  107
ARTS                      103
TEACHER                   102
APPAREL                    97
DIGITAL-MEDIA              96
AGRICULTURE                63
AUTOMOBILE                 36
BPO                        22
Name: count, dtype: int64

In [8]:
resume_df["Resume_str"].iloc[0]

"         HR ADMINISTRATOR/MARKETING ASSOCIATE\n\nHR ADMINISTRATOR       Summary     Dedicated Customer Service Manager with 15+ years of experience in Hospitality and Customer Service Management.   Respected builder and leader of customer-focused teams; strives to instill a shared, enthusiastic commitment to customer service.         Highlights         Focused on customer satisfaction  Team management  Marketing savvy  Conflict resolution techniques     Training and development  Skilled multi-tasker  Client relations specialist           Accomplishments      Missouri DOT Supervisor Training Certification  Certified by IHG in Customer Loyalty and Marketing by Segment   Hilton Worldwide General Manager Training Certification  Accomplished Trainer for cross server hospitality systems such as    Hilton OnQ  ,   Micros    Opera PMS   , Fidelio    OPERA    Reservation System (ORS) ,   Holidex    Completed courses and seminars in customer service, sales strategies, inventory control, loss prevention, safety, time management, leadership and performance assessment.        Experience      HR Administrator/Marketing Associate\n\nHR Administrator     Dec 2013   to   Current      Company Name   －   City  ,   State     Helps to develop policies, directs and coordinates activities such as employment, compensation, labor relations, benefits, training, and employee services.  Prepares employee separation notices and related documentation  Keeps records of benefits plans participation such as insurance and pension plan, personnel transactions such as hires, promotions, transfers, performance reviews, and terminations, and employee statistics for government reporting.  Advises management in appropriate resolution of employee relations issues.  Administers benefits programs such as life, health, dental, insurance, pension plans, vacation, sick leave, leave of absence, and employee assistance.     Marketing Associate \xa0   Designed and created marketing collateral for sales meetings, trade shows and company executives.  Managed the in-house advertising program consisting of print and media collateral pieces.  Assisted in the complete design and launch of the company's website in 2 months.  Created an official company page on Facebook to facilitate interaction with customers.  Analyzed ratings and programming features of competitors to evaluate the effectiveness of marketing strategies.         Advanced Medical Claims Analyst     Mar 2012   to   Dec 2013      Company Name   －   City  ,   State     Reviewed medical bills for the accuracy of the treatments, tests, and hospital stays prior to sanctioning the claims.  Trained to interpret the codes (ICD-9, CPT) and terminology commonly used in medical billing to fully understand the paperwork that is submitted by healthcare providers.  Required to have organizational and analytical skills as well as computer skills, knowledge of medical terminology and procedures, statistics, billing standards, data analysis and laws regarding medical billing.         Assistant General Manager     Jun 2010   to   Dec 2010      Company Name   －   City  ,   State     Performed duties including but not limited to, budgeting and financial management, accounting, human resources, payroll and purchasing.  Established and maintained close working relationships with all departments of the hotel to ensure maximum operation, productivity, morale and guest service.  Handled daily operations and reported directly to the corporate office.  Hired and trained staff on overall objectives and goals with an emphasis on high customer service.  Marketing and Advertising, working on public relations with the media, government and local businesses and Chamber of Commerce.         Executive Support / Marketing Assistant     Jul 2007   to   Jun 2010      Company Name   －   City  ,   State     Provided assistance to various department heads - Executive, Marketing, Customer Service, Human Resources.  Managed front-end operations to ensure friendly and efficient transactions.  Ensured the swift resolution of customer issues to preserve customer loyalty while complying with company policies.  Exemplified the second-to-none customer service delivery in all interactions with customers and potential clients.         Reservation & Front Office Manager     Jun 2004   to   Jul 2007      Company Name   －   City  ,   State          Owner/ Partner     Dec 2001   to   May 2004      Company Name   －   City  ,   State          Price Integrity Coordinator     Aug 1999   to   Dec 2001      Company Name   －   City  ,   State          Education      N/A  ,   Business Administration   1999     Jefferson College   －   City  ,   State       Business Administration  Marketing / Advertising         High School Diploma  ,   College Prep. studies   1998     Sainte Genevieve Senior High   －   City  ,   State       Awarded American Shrubel Leadership Scholarship to Jefferson College         Skills     Accounting, ads, advertising, analytical skills, benefits, billing, budgeting, clients, Customer Service, data analysis, delivery, documentation, employee relations, financial management, government relations, Human Resources, insurance, labor relations, layout, Marketing, marketing collateral, medical billing, medical terminology, office, organizational, payroll, performance reviews, personnel, policies, posters, presentations, public relations, purchasing, reporting, statistics, website.    "

In [9]:
job_df = pd.read_csv(
    "../datasets/raw/job_descriptions/job_descriptions.csv",
    nrows=10000
)
job_df.head()

,Job Id,Experience,Qualifications,Salary Range,location,Country,latitude,longitude,Work Type,Company Size,...,Contact,Job Title,Role,Job Portal,Job Description,Benefits,skills,Responsibilities,Company,Company Profile
0,1089843540111562,5 to 15 Years,M.Tech,$59K-$99K,Douglas,Isle of Man,54.2361,-4.5481,Intern,26801,...,001-381-930-7517x737,Digital Marketing Specialist,Social Media Manager,Snagajob,Social Media Managers oversee an organizations...,"{'Flexible Spending Accounts (FSAs), Relocatio...","Social media platforms (e.g., Facebook, Twitte...","Manage and grow social media accounts, create ...",Icahn Enterprises,"{""Sector"":""Diversified"",""Industry"":""Diversifie..."
1,398454096642776,2 to 12 Years,BCA,$56K-$116K,Ashgabat,Turkmenistan,38.9697,59.5563,Intern,100340,...,461-509-4216,Web Developer,Frontend Web Developer,Idealist,Frontend Web Developers design and implement u...,"{'Health Insurance, Retirement Plans, Paid Tim...","HTML, CSS, JavaScript Frontend frameworks (e.g...","Design and code user interfaces for websites, ...",PNC Financial Services Group,"{""Sector"":""Financial Services"",""Industry"":""Com..."
2,481640072963533,0 to 12 Years,PhD,$61K-$104K,Macao,"Macao SAR, China",22.1987,113.5439,Temporary,84525,...,9687619505,Operations Manager,Quality Control Manager,Jobs2Careers,Quality Control Managers establish and enforce...,"{'Legal Assistance, Bonuses and Incentive Prog...",Quality control processes and methodologies St...,Establish and enforce quality control standard...,United Services Automobile Assn.,"{""Sector"":""Insurance"",""Industry"":""Insurance: P..."
3,688192671473044,4 to 11 Years,PhD,$65K-$91K,Porto-Novo,Benin,9.3077,2.3158,Full-Time,129896,...,+1-820-643-5431x47576,Network Engineer,Wireless Network Engineer,FlexJobs,"Wireless Network Engineers design, implement, ...","{'Transportation Benefits, Professional Develo...",Wireless network design and architecture Wi-Fi...,"Design, configure, and optimize wireless netwo...",Hess,"{""Sector"":""Energy"",""Industry"":""Mining, Crude-O..."
4,117057806156508,1 to 12 Years,MBA,$64K-$87K,Santiago,Chile,-35.6751,-71.5429,Intern,53944,...,343.975.4702x9340,Event Manager,Conference Manager,Jobs2Careers,A Conference Manager coordinates and manages c...,"{'Flexible Spending Accounts (FSAs), Relocatio...",Event planning Conference logistics Budget man...,Specialize in conference and convention planni...,Cairn Energy,"{""Sector"":""Energy"",""Industry"":""Energy - Oil & ..."

In [10]:
job_df.head()

,Job Id,Experience,Qualifications,Salary Range,location,Country,latitude,longitude,Work Type,Company Size,...,Contact,Job Title,Role,Job Portal,Job Description,Benefits,skills,Responsibilities,Company,Company Profile
0,1089843540111562,5 to 15 Years,M.Tech,$59K-$99K,Douglas,Isle of Man,54.2361,-4.5481,Intern,26801,...,001-381-930-7517x737,Digital Marketing Specialist,Social Media Manager,Snagajob,Social Media Managers oversee an organizations...,"{'Flexible Spending Accounts (FSAs), Relocatio...","Social media platforms (e.g., Facebook, Twitte...","Manage and grow social media accounts, create ...",Icahn Enterprises,"{""Sector"":""Diversified"",""Industry"":""Diversifie..."
1,398454096642776,2 to 12 Years,BCA,$56K-$116K,Ashgabat,Turkmenistan,38.9697,59.5563,Intern,100340,...,461-509-4216,Web Developer,Frontend Web Developer,Idealist,Frontend Web Developers design and implement u...,"{'Health Insurance, Retirement Plans, Paid Tim...","HTML, CSS, JavaScript Frontend frameworks (e.g...","Design and code user interfaces for websites, ...",PNC Financial Services Group,"{""Sector"":""Financial Services"",""Industry"":""Com..."
2,481640072963533,0 to 12 Years,PhD,$61K-$104K,Macao,"Macao SAR, China",22.1987,113.5439,Temporary,84525,...,9687619505,Operations Manager,Quality Control Manager,Jobs2Careers,Quality Control Managers establish and enforce...,"{'Legal Assistance, Bonuses and Incentive Prog...",Quality control processes and methodologies St...,Establish and enforce quality control standard...,United Services Automobile Assn.,"{""Sector"":""Insurance"",""Industry"":""Insurance: P..."
3,688192671473044,4 to 11 Years,PhD,$65K-$91K,Porto-Novo,Benin,9.3077,2.3158,Full-Time,129896,...,+1-820-643-5431x47576,Network Engineer,Wireless Network Engineer,FlexJobs,"Wireless Network Engineers design, implement, ...","{'Transportation Benefits, Professional Develo...",Wireless network design and architecture Wi-Fi...,"Design, configure, and optimize wireless netwo...",Hess,"{""Sector"":""Energy"",""Industry"":""Mining, Crude-O..."
4,117057806156508,1 to 12 Years,MBA,$64K-$87K,Santiago,Chile,-35.6751,-71.5429,Intern,53944,...,343.975.4702x9340,Event Manager,Conference Manager,Jobs2Careers,A Conference Manager coordinates and manages c...,"{'Flexible Spending Accounts (FSAs), Relocatio...",Event planning Conference logistics Budget man...,Specialize in conference and convention planni...,Cairn Energy,"{""Sector"":""Energy"",""Industry"":""Energy - Oil & ..."

In [11]:
job_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 23 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Job Id            10000 non-null  int64
 1   Experience        10000 non-null  str
 2   Qualifications    10000 non-null  str
 3   Salary Range      10000 non-null  str
 4   location          10000 non-null  str
 5   Country           10000 non-null  str
 6   latitude          10000 non-null  float64
 7   longitude         10000 non-null  float64
 8   Work Type         10000 non-null  str
 9   Company Size      10000 non-null  int64
 10  Job Posting Date  10000 non-null  str
 11  Preference        10000 non-null  str
 12  Contact Person    10000 non-null  str
 13  Contact           10000 non-null  str
 14  Job Title         10000 non-null  str
 15  Role              10000 non-null  str
 16  Job Portal        10000 non-null  str
 17  Job Description   10000 non-null  str
 18  Benefits          10000 non-null  str
 19  skills            10000 non-null  str
 20  Responsibilities  10000 non-null  str
 21  Company           10000 non-null  str
 22  Company Profile   9964 non-null   str
dtypes: float64(2), int64(2), str(19)
memory usage: 1.8 MB

In [12]:
job_df[
    [
        "Job Title",
        "Role",
        "skills",
        "Job Description"
    ]
].head()

,Job Title,Role,skills,Job Description
0,Digital Marketing Specialist,Social Media Manager,"Social media platforms (e.g., Facebook, Twitte...",Social Media Managers oversee an organizations...
1,Web Developer,Frontend Web Developer,"HTML, CSS, JavaScript Frontend frameworks (e.g...",Frontend Web Developers design and implement u...
2,Operations Manager,Quality Control Manager,Quality control processes and methodologies St...,Quality Control Managers establish and enforce...
3,Network Engineer,Wireless Network Engineer,Wireless network design and architecture Wi-Fi...,"Wireless Network Engineers design, implement, ..."
4,Event Manager,Conference Manager,Event planning Conference logistics Budget man...,A Conference Manager coordinates and manages c...

In [13]:
job_text = (job_df["Job Title"] + job_df["skills"] + job_df["Job Description"])

In [14]:
job_text

0       Digital Marketing SpecialistSocial media platf...
1       Web DeveloperHTML, CSS, JavaScript Frontend fr...
2       Operations ManagerQuality control processes an...
3       Network EngineerWireless network design and ar...
4       Event ManagerEvent planning Conference logisti...
                              ...
9995    Financial AnalystFinancial planning Investment...
9996    Procurement SpecialistProcurement strategies S...
9997    Project CoordinatorProject planning and schedu...
9998    Architectural DesignerInterior design Space pl...
9999    Substance Abuse CounselorFamily counseling Mar...
Length: 10000, dtype: str

In [15]:
job_df["combined_text"] = (job_df["Job Title"].astype(str) + " " + job_df["skills"].astype(str) + " " + job_df["Job Description"].astype(str))

In [16]:
job_df["combined_text"]

0       Digital Marketing Specialist Social media plat...
1       Web Developer HTML, CSS, JavaScript Frontend f...
2       Operations Manager Quality control processes a...
3       Network Engineer Wireless network design and a...
4       Event Manager Event planning Conference logist...
                              ...
9995    Financial Analyst Financial planning Investmen...
9996    Procurement Specialist Procurement strategies ...
9997    Project Coordinator Project planning and sched...
9998    Architectural Designer Interior design Space p...
9999    Substance Abuse Counselor Family counseling Ma...
Name: combined_text, Length: 10000, dtype: str

In [17]:
print(job_df["combined_text"].iloc[0][:1500])

Digital Marketing Specialist Social media platforms (e.g., Facebook, Twitter, Instagram) Content creation and scheduling Social media analytics and insights Community engagement Paid social advertising Social Media Managers oversee an organizations social media presence. They create and schedule content, engage with followers, and analyze social media metrics to drive brand awareness and engagement.

In [18]:
pip install nltk

Requirement already satisfied: nltk in /home/krish/AI-Interview-Intelligence-Platform/venv/lib/python3.12/site-packages (3.9.4)
Requirement already satisfied: click in /home/krish/AI-Interview-Intelligence-Platform/venv/lib/python3.12/site-packages (from nltk) (8.4.1)
Requirement already satisfied: joblib in /home/krish/AI-Interview-Intelligence-Platform/venv/lib/python3.12/site-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /home/krish/AI-Interview-Intelligence-Platform/venv/lib/python3.12/site-packages (from nltk) (2026.5.9)
Requirement already satisfied: tqdm in /home/krish/AI-Interview-Intelligence-Platform/venv/lib/python3.12/site-packages (from nltk) (4.68.2)
Note: you may need to restart the kernel to use updated packages.

In [19]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

In [20]:
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package stopwords to /home/krish/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /home/krish/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /home/krish/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

True

In [21]:
stop_words = set(stopwords.words('english'))
lemmatizer = wordnet_lemmatizer = WordNetLemmatizer()
def clean_text(text):
    text = str(text)
    text = re.sub(r'[^\w\s]', '', text)
    text = text.lower()
    words = text.split()
    tokens = [lemmatizer.lemmatize(word) for word in words if word not in stop_words]
    return ' '.join(tokens)

In [22]:
resume_df["cleaned_resume"] = resume_df["Resume_str"].apply(clean_text)

In [23]:
job_df["clean_job"] = (
    job_df["combined_text"]
    .apply(clean_text)
)

In [24]:
resume_df["cleaned_resume"].head()

0    hr administratormarketing associate hr adminis...
1    hr specialist u hr operation summary versatile...
2    hr director summary 20 year experience recruit...
3    hr specialist summary dedicated driven dynamic...
4    hr manager skill highlight hr skill hr departm...
Name: cleaned_resume, dtype: str

In [25]:
job_df["clean_job"].head()

0    digital marketing specialist social medium pla...
1    web developer html cs javascript frontend fram...
2    operation manager quality control process meth...
3    network engineer wireless network design archi...
4    event manager event planning conference logist...
Name: clean_job, dtype: str

In [26]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer(
    "all-MiniLM-L6-v2"
)

/home/krish/AI-Interview-Intelligence-Platform/venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 2681.36it/s]

In [27]:
resume_embeddings = model.encode(
    resume_df["cleaned_resume"].tolist(),
    show_progress_bar=True
    
)

Batches: 100%|██████████| 78/78 [03:28<00:00,  2.67s/it]

In [28]:
resume_embeddings.shape

(2484, 384)

In [29]:
job_embeddings = model.encode(
    job_df["clean_job"].tolist(),
    show_progress_bar=True
)

Batches:   0%|          | 0/313 [00:00<?, ?it/s]

Batches: 100%|██████████| 313/313 [02:01<00:00,  2.57it/s]

In [30]:
job_embeddings.shape

(10000, 384)

In [31]:
print(resume_embeddings.shape)

print(job_embeddings.shape)

(2484, 384)
(10000, 384)

In [32]:
job_df.shape

(10000, 25)

In [33]:
from sklearn.metrics.pairwise import cosine_similarity

similarity_matrix = cosine_similarity(
    job_embeddings,
    resume_embeddings
)

In [34]:
job_index = 0

best_resume_idx = similarity_matrix[job_index].argmax()

best_score = similarity_matrix[job_index][best_resume_idx]

print("Best Resume Index:", best_resume_idx)
print("Similarity Score:", best_score)

print("\nResume Category:")
print(resume_df.iloc[best_resume_idx]["Category"])

Best Resume Index: 1285
Similarity Score: 0.6573839

Resume Category:
DIGITAL-MEDIA

In [35]:
top5_indices = similarity_matrix[job_index].argsort()[-5:][::-1]
print("\nTop 5 Resume Indices:", top5_indices)
print("Top 5 Similarity Scores:", similarity_matrix[job_index][top5_indices])
print("\nTop 5 Resume Categories:")
for idx in top5_indices:
    print(f"Index: {idx}, Category: {resume_df.iloc[idx]['Category']}")

Top 5 Resume Indices: [1285 2127 2090 1267 1619]
Top 5 Similarity Scores: [0.6573839 0.6483636 0.639284  0.6298071 0.6255728]

Top 5 Resume Categories:
Index: 1285, Category: DIGITAL-MEDIA
Index: 2127, Category: PUBLIC-RELATIONS
Index: 2090, Category: PUBLIC-RELATIONS
Index: 1267, Category: DIGITAL-MEDIA
Index: 1619, Category: APPAREL

In [36]:
def get_top_matches(job_index, top_n=5):
    score = similarity_matrix[job_index]
    top_indices = similarity_matrix[job_index].argsort()[-top_n:][::-1]
    results = []
    for idx in top_indices:
        results.append({
            "resume_index": idx,
            "category": resume_df.iloc[idx]['Category'],
            "similarity_score": score[idx]
        })
    return pd.DataFrame(results)

In [37]:
get_top_matches(0)

   resume_index          category  similarity_score
0          1285     DIGITAL-MEDIA          0.657384
1          2127  PUBLIC-RELATIONS          0.648364
2          2090  PUBLIC-RELATIONS          0.639284
3          1267     DIGITAL-MEDIA          0.629807
4          1619           APPAREL          0.625573

In [38]:
import numpy as np

np.save(
    "../models/resume_embeddings.npy",
    resume_embeddings
)

In [39]:
import os

os.listdir("../models")

['.gitkeep', 'resume_embeddings.npy', 'trained', 'checkpoints']

In [41]:
print(
    resume_df.iloc[930]["Resume_str"][:1500]
)

         FEDERAL GRAIN INSPECTOR         Summary     Service-oriented Process Operator with 5 years background working in the Industrial Industry. Core competencies  include Processing, Observing, Analyzing chemicals and other matters, as well as excellent communication and time management skills. Handle tasks with accuracy and efficiency.       Skills          Production and Processing  Industrial and Environmental safety  Mechanical aptitude and equipment troubleshooting ability.  Basic math skills and the ability to compute decimals and perentage.           Basic computer skills    Good oral and written communication skills    Previous manufacturing skills    Able to lift up to 70 pounds, use tools    Team work             Experience      Company Name    City  ,   State    Federal Grain Inspector   06/2015   to   Current      Prepare grain samples for grading by preforming the necessary tests to determine moisture content, test weight, dockage, and presence of foreign material.  Perform specialized tests such as aflatoxin and protein analysis; calibrates equipment, grind samples, read results and enters reading on official certificates.  Inspect ship holds for loading, and safety procedures.          Company Name    City  ,   State    Process Operator Intern   06/2015   to   09/2015      Monitor equipment functioning, observe temperature levels, and flow gauges. Perform regular unit checks  in order to ensure that all equipment is operating as it should.  Control equipment